### ISSUE TITLE
Calling file locations poorly

### ISSUE THREAD

**Issue by growdev** [growdev/woocommerce-template-hints#6]
From wp.org:
## Calling file locations poorly

The way your plugin is referencing other files is not going to work with all setups of WordPress.

$core = ( strpos( $located, 'wp-content/plugins/' ) !== false ) ? 'core' : 'theme';

When you hardcode in paths, or assume that everyone has WordPress in the root of their domain, you cause anyone using 'Giving WordPress it's own directory' (a VERY common setup) to break. In addition, WordPress allows users to change the name of wp-content, so you would break anyone who choses to do so.

Please review http://codex.wordpress.org/Determining_Plugin_and_Content_Directories and update your plugin accordingly. And don't worry about supporting WordPress 2.x or lower. We don't encourage it nor expect you to do so, so save yourself some time and energy.

When you've corrected your code, reply to this email with the updated code attached as a zip, or provide a link to the new code for us to review.

cc: @bryceadams

**Comment by bryceadams** [comment]
:weary: will fix weekend/next week

**Comment by growdev** [comment]
I'll take care of it 👍

**Comment by growdev** [comment]
Fixed and plugin deployed to w.org.
